### ISSUE TITLE
Kubernetes support?

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#19]
What should Faktory look like in a world full of Kubernetes?  My understanding is that Kubernetes could be very useful in scaling worker processes as queues grow.  How can Faktory make this easy?

**Comment by jbielick** [comment]
The newer implementations of the [Horizontal Pod Autoscaler] (HPA 1.6+?) support scaling on [Custom Metrics] ([k8s 1.8+ custom metrics]), for which there are [some preliminary implementations]. I think one interesting one is the [Prometheus Adapter]—if I understand correctly, k8s can pull metrics from prometheus and then an HPA can be set to scale based on a metric in that set. Perhaps in this world the responsibility of Faktory would be to have a prometheus exporter (á la [oliver006/redis_exporter]) that can send metics to Prometheus. 

Since an exporter might live separately, I believe at a fundamental level the basic necessity would be Faktory's API for exposing process metrics. An obvious metric for scaling might be the size of the queues, but I have also found myself interested in the _amount of time a job spends in the queue before processing_ as well, because I believe that's also an intelligent indicator of a need to scale up workers.

Are there current ideas / plans for what internal metrics will be gathered / recorded?

[Horizontal Pod Autoscaler]: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
[Custom Metrics]: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/custom-metrics-api.md
[some preliminary implementations]: https://github.com/kubernetes/metrics/blob/master/IMPLEMENTATIONS.md
[Prometheus Adapter]: https://github.com/directxman12/k8s-prometheus-adapter
[k8s 1.8+ custom metrics]: https://blog.openshift.com/kubernetes-1-8-now-custom-metrics/
[oliver006/redis_exporter]: https://github.com/oliver006/redis_exporter

**Comment by mperham** [comment]
Yeah, queue size and latency are easily implementable.

What's the best approach to getting Kubernetes aware of Faktory?  Are people using Helm?  Would a Docker image or DEB/RPM binaries be most useful?

**Comment by syndbg** [comment]
@mperham Definitely Docker image would enable `faktory` to be used everywhere. Be that Kubernetes, Mesos Marathon/Aurora, Nomad and etc.

**Comment by rosskevin** [comment]
We run google container engine a.k.a. GKE (managed kubernetes) for all our services which include sidekiq workers.  We have a situation where we may have high flash traffic (pdf rendering) where we are going to use google cloud functions a.k.a. GCF so we don't worry about scale. So sidekiq handles typical jobs, GCF handles high scale/flash traffic jobs like rendering.

With the introduction of faktory, I think one approach/architecture for pain-free scaling:
- kubernetes `service` + `deployment` for faktory
- kubernetes `deployment` for ruby worker (migrate sidekiq jobs)
- [google cloud functions](https://cloud.google.com/functions/) (GCP's answer for serverless) for something like `faktory_worker_node_gcf` worker (no scale/cluster management needed)

Faktory needs proper [probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/):
- readiness - ready for traffic
- liveness - lightest ping possible

Preparing for kubernetes:
- some people use helm, but I haven't found it very heavily trafficked.  Nonetheless, a reference helm config helps others develop their own configs (and can be used as a quickstart)
- many are using spinnaker for continuous deployment (e.g. based on vanilla kubernetes yaml files)
- optimized docker image would be most useful - e.g. redis-alpine
- persistent storage of faktory itself and ensuring recovery/availability will be most important concern for most.  


Last but not least, consider an equivalent service to redislabs.com.  We use GKE because we want to offload as much management as possible to focus on app development. For that reason, we didn't even try to deploy redis inside our cluster, but we used redislabs.com to deploy in the same region as our GKE cluster.  Feel free to ping me via email if you want to dig into any of these areas.

**Comment by mperham** [comment]
@rosskevin Thanks for the info, that's great detail.  Running a Faktory SaaS is not in my immediate plans but like antirez and Redislabs, I've already had pings from people interested in partnering in building something and I'm always willing to chat: mike @ contribsys.com

I'm still trying to wrap my head around what an enterprise-ready Faktory would look like and require; this helps a lot.

**Comment by gmaliar** [comment]
@rosskevin @mperham a few notes to add about k8s support, let me know what you think and if I'm getting anything wrong.

![contribsys/faktory](https://github.com/contribsys/faktory) is the master process that also holds the rocksdb database, remember that k8s might kill faktory pod at will, so there should be a service with both web and worker ports open connected to the `faktory-master` deployment.
the deployment itself should have a ![persistent volume claim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), so that the actual database file will be mounted on that volume, otherwise you'd lose all jobs waiting to be fulfilled, 
this looks _okay_ https://github.com/contribsys/faktory/blob/01dadde5100fb5a4a85ea61d6cd990eda02e4d39/cli/cli.go#L52 as it allows you to specify in the deployment yaml under the command key but it might be a better approach to allow everything to be specified as environment variables, i.e password, port, storage directory, no-tls etc.

I am a heavy helm user, it's pretty easy to set up a basic chart that will take care of setting up the faktory server, but workers might need to be as a different chart, so upgrading of the worker chart won't require a redeploy of the faktory server.

**Comment by vamsi248** [comment]
Hello can u help me in the small issue....
i have initialized master successfully but the issue is, when i run the command " kubectl get nodes " master status is showing not ready..
2. in nodes it was saying successfully reached response and you can enter kubectl get nodes in master..
but its not showing in master. only master is showing as not ready.

**Comment by mickuehl** [comment]
I will look into configuration & deployment for OpenShift ... similar to Kubernetes ...

**Comment by vamsi248** [comment]
halo can any one help me....
why my leavness and readiness probes are failing in my ntginx-ingress-controller.. any idea....
in my logs i am getting this 

I1201 00:19:48.746923       7 shared_informer.go:112] stop requested
E1201 00:19:48.746985       7 listers.go:63] Timed out waiting for caches to sync
[notice] 22#22: signal process started
 shutting down Ingress controller...
 Handled quit, awaiting pod deletion
I NGINX process has stopped
 Exiting with 0


can any one have idea... is my configuration fault or????

**Comment by mperham** [comment]
Gonna close this because I'm not a fan of nebulous, open-ended issues.  Please open a specific issue if there's something Faktory can do to make our k8s support better.

**Comment by kirs** [comment]
@mperham I was going to open an issue regarding Kubernetes support, and I discovered you have one already open!

Specifically, I'd like to see examples of Kubernetes YAMLs that people could copy, paste, `kubectl apply` and have Faktory running.

This would be especially cool to have for zero-downtime deploy of Faktory, as well as for Redis Gateway and replicated Faktory Pro.

**Comment by jbielick** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  name: faktory
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  namespace: faktory
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-east1-b
---
apiVersion: v1
kind: Service
metadata:
  namespace: faktory
  labels:
    name: faktory
  name: faktory
spec:
  ports:
    - name: faktory
      protocol: TCP
      port: 7419
      targetPort: 7419
  selector:
    app: faktory
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: faktory
  name: faktory-conf
data:
  cron.toml: |
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: faktory
  name: faktory
spec:
  serviceName: faktory
  replicas: 1
  template:
    metadata:
      namespace: faktory
      labels:
        app: faktory
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: faktory
          image: contribsys/faktory:0.9.6
          command:
            - /faktory
            - -b
            - :7419
            - -w
            - :7420
            - -e
            - production
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
          env:
            - name: FAKTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: password
          ports:
            - containerPort: 7419
              name: faktory
          volumeMounts:
            - name: faktory-data
              mountPath: /var/lib/faktory/db
            - name: faktory-conf
              mountPath: /etc/faktory/conf.d
      volumes:
        - name: faktory-conf
          configMap:
            name: faktory-conf
            items:
              - key: cron.toml
                path: cron.toml
  volumeClaimTemplates:
    - metadata:
        name: faktory-data
        namespace: faktory
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

**Comment by Dm3Ch** [comment]
Here's a helm chart https://github.com/helm/charts/pull/13974

**Comment by ecdemis123** [comment]
Here's the resources I used to Faktory server fully set up. I hope that this can help someone else in the future, as @jbielick 's example deployment yml was a great help to me. 

A note about this configuration, we are using Datadog deployed as a daemon set + Kubernetes, so this setup will allow you to use the "pro metrics" statsd implementation. The references to DD_TRACE_AGENT_HOSTNAME are how we access the datadog agent.

Configs created:
 `kubectl create secret generic faktory --from-literal=password=${your_password} --from-literal=username=${your_username} --from-literal=license=${your_license}`

`kubectl create configmap faktory-cron-config --from-file=cron.toml=path/to/file/cron.toml -o yaml --dry-run | kubectl apply -f -`

`kubectl create configmap faktory-statsd-config --from-file=statsd.toml=path/to/file/statsd.toml -o yaml --dry-run | kubectl apply -f -`

Server Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faktory
  labels:
    run: faktory
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        run: faktory
        name: faktory
      annotations:
        key: value
    spec:
      containers:
        - name: faktory
          image: 'link to your faktory pro docker image'
          command: [ "/faktory"]
          # must use "production" flag for cron
          args: ["-w", ":7420", "-b", ":7419", "-e", "production"]
          ports:
            - containerPort: 7419
            - containerPort: 7420
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
          env:
            - name: FAKTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: password
            - name: FAKTORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: username
            - name: FAKTORY_LICENSE
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: license
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: faktory-data
              mountPath: /var/lib/faktory/db
            - name: faktory-cron-config
              mountPath: /etc/faktory/conf.d/cron.toml
              subPath: cron.toml
            - name: shared
              mountPath: /etc/faktory/conf.d/statsd.toml
              subPath: statsd.toml
      initContainers:
        - name: config-data
          image: busybox
          command:
            - sh
            - -c
            - cp /statsd/statsd.toml /shared/statsd.toml && sed -i 's/localhost/'"$DD_TRACE_AGENT_HOSTNAME"'/g' /shared/statsd.toml
          env:
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: faktory-statsd-config
              mountPath: /statsd/
            - name: shared
              mountPath: /shared/
      volumes:
        - name: faktory-cron-config
          configMap:
            name: faktory-cron-config
            items:
              - key: cron.toml
                path: cron.toml
        - name: faktory-statsd-config
          configMap:
            name: faktory-statsd-config
            items:
              - key: statsd.toml
                path: statsd.toml
        - name: shared
          emptyDir: {}
        - name: faktory-data
          persistentVolumeClaim:
            claimName: faktory-data
---
kind: Service
apiVersion: v1
metadata:
  name: faktory
  labels:
    run: faktory
spec:
  selector:
    run: faktory
  ports:
  - name: network
    protocol: TCP
    port: 7419
    targetPort: 7419
  - name: webui
    protocol: TCP
    port: 80
    targetPort: 7420
```

Persistent Volume Claim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faktory-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

This is a script for sending the HUP signal to the Faktory server to reset the cron when new jobs are added:
```
#!/bin/bash

# This script reloads the configuration of the Faktory job server deployment
# by sending the HUP signal to the Faktory docker container
# https://github.com/contribsys/faktory/wiki/Pro-Cron

echo "Updating Faktory cron config and reloading Faktory server config"

PROJECT_DIR="$( cd "$( dirname "$DIR" )" && pwd )"

kubectl create configmap faktory-cron-config --from-file=cron.toml=${PROJECT_DIR}/path/to/file/cron.toml -o yaml --dry-run | kubectl apply -f -

POD=`kubectl get --no-headers=true pods -l name=faktory -o custom-columns=:metadata.name`

if [[  -z "$POD" ]] ; then
    echo "No Faktory Pods Found"
    exit 1
fi

echo "Faktory pod: ${POD}"

kubectl exec -it ${POD} -c=faktory -- /bin/kill -HUP 1

echo "Done"
exit 0
```

I hope this helps someone else with their setup!

**Comment by jbielick** [comment]
@dm3ch I saw that the incubator PR was closed. Did you end up adding your chart / repo to the helm hub? I couldn't find it. Would you be opposed to me using some of the files from your PR to make a chart and publish?

@ecdemis123 this is great. I assume this is a production setup? Glad you figured out the Datadog DaemonSet connection. I'll definitely be referencing that at some point to get it working correctly in one of our clusters. That `initContainer` is a clever workaround for interpolating the ENV var in the config. 

I think I'll start on a helm chart, which _could_ automate sending the `SIGHUP` (is it not a `USR1` signal?) upon changing of a cron config. I'll post here if I have some progress to show. Is baking in some datadog support a good idea? I know Sidekiq does this and I could borrow @ecdemis123's solution there.

**Comment by ecdemis123** [comment]
Cheers! Yep, this is our production setup, however our staging setup is pretty much the same with the exception that it's running faktory in development mode.  

I'll be interested to see the helm chart. We aren't currently using helm but we hope to move onto it someday.

**Comment by ecdemis123** [comment]
Actually, that HUP command is not working to restart the cron. I suspect that its due to this https://github.com/kubernetes/kubernetes/issues/50345 since I'm using subPath to mount the conf.d files. Gonna dig more into it and see if I can come up with a workaround

**Comment by jbielick** [comment]
@ecdemis123 You might consider writing the ConfigMap like so:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: faktory
data:
  cron.toml: |
    [[cron]]
      schedule = "*/5 * * * *"
      [cron.job]
        type = "FiveJob"
        queue = "critical"
        [cron.job.custom]
          foo = "bar"

    [[cron]]
      schedule = "12 * * * *"
      [cron.job]
        type = "HourlyReport"
        retry = 3

    [[cron]]
      schedule = "* * * * *"
      [cron.job]
        type = "EveryMinute"
  faktory.toml: ""
  test.toml: ""
```

Where each key is a file, the value its string contents.

I found this pretty convenient when mounting to the pod:

```yaml
# ...
            - name: faktory-configs
              mountPath: /etc/faktory/conf.d
# ...
      volumes:
        - name: faktory-configs
          configMap:
            name: faktory
```

```
› kubectl exec faktory-0 -- ls -al /etc/faktory/conf.d
total 12
drwxrwxrwx    3 root     root          4096 Sep 14 23:21 .
drwxr-xr-x    1 root     root          4096 Sep 14 23:14 ..
drwxr-xr-x    2 root     root          4096 Sep 14 23:21 ..2019_09_14_23_21_59.171278579
lrwxrwxrwx    1 root     root            31 Sep 14 23:21 ..data -> ..2019_09_14_23_21_59.171278579
lrwxrwxrwx    1 root     root            16 Sep 14 23:14 cron.toml -> ..data/cron.toml
lrwxrwxrwx    1 root     root            19 Sep 14 23:14 faktory.toml -> ..data/faktory.toml
lrwxrwxrwx    1 root     root            16 Sep 14 23:14 test.toml -> ..data/test.toml
```

Change to the ConfigMap get pushed to the pod in less than a minute (10s in my case).

> As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period (1 minute by default) + ttl of ConfigMaps cache (1 minute by default) in kubelet.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by jbielick** [comment]
You might be able to _write_ the statds.toml in the init container and it won't get overwritten. That's kind of a tricky one :\

The reloading (`kill -HUP 1`) seems to work (once the files were fully pushed out). I'm thinking it might be a good idea to have a sidecar container watching those files and when they change, send a signal to the other container in the pod.

I'll do an experiment and report back. This ability is mentioned here: https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

**Comment by ecdemis123** [comment]
Interesting. My config map was created from a file, not using a string, so I wonder if that would simplify the implementation a bit. Mine looks pretty similar to yours, but I'm not that familiar with configmaps to see any subtle differences.  I like the idea of having a sidecar container to send the HUP signal.  I added that HUP script referenced above to our deploy pipeline that will get ran manually if necessary.

```kubectl describe configmap faktory-config-merged
Name:         faktory-config-merged
Namespace:    default
Labels:       <none>
Annotations:  "truncated for now"

Data
====
cron.toml:
----
[[cron]]
  schedule = "12 * * * *"
  [cron.job]
    type = "TestDatadog"
    retry = 1
[[cron]]
  schedule = "*/5 * * * *"
  [cron.job]
    type = "UpdateChatAgentCount"
    retry = 0

statsd.toml:
----
[statsd]
  # required, location of the statsd server
  location = "localhost:8125"

  # Prepend all metric names with this value, defaults to 'faktory.'
  # If you have multiple Faktory servers for multiple apps reporting to
  # the same statsd server you can use a multi-level namespace,
  # e.g. "app1.faktory.", "app2.faktory." or use a tag below.
  namespace = "faktory."

  # optional, DataDog-style tags to send with each metric.
  # keep in mind that every tag is sent with every metric so keep tags short.
  tags = ["env:production"]

  # Statsd client will buffer metrics for 100ms or until this size is reached.
  # The default value of 15 tries to avoid UDP packet sizes larger than 1500 bytes.
  # If your network supports jumbo UDP packets, you can increase this to ~50.
  #bufferSize = 15

Events:  <none>```

**Comment by ecdemis123** [comment]
I realized that I also could have posted our worker deployment yml.  This just a basic implementation and I've removed company-specific info.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faktory-worker
  labels:
    run: faktory-worker
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        run: faktory-worker
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: task-pool
      volumes:
        - name: cloudsql
          emptyDir: null
      containers:
        - name: cloudsql-proxy
          image: 'gcr.io/cloudsql-docker/gce-proxy:1.10'
          command:
            - '/cloud_sql_proxy'
            - '--dir=/cloudsql'
            - '-instances=instance-id'
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          lifecycle:
            preStop:
              exec:
                command: ['/bin/sh', '-c', '/bin/sleep 30']
        - name: faktory-worker
          imagePullPolicy: Always
          image: 'our repo docker image'
          command: ['node', 'dist/src/jobs/faktory/index.js']
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          env:
            - name: FAKTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: password
            - name: FAKTORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: faktory
                  key: username
            - name: DB_SOCKETPATH
              value: /cloudsql/socket-path
            - name: FAKTORY_URL
              value: "tcp://:$(FAKTORY_PASSWORD)@faktory:7419"
            - name: DEBUG
              value: faktory*
            - name: DD_SERVICE_NAME
              value: faktory-worker
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: #### company secrets
            - configMapRef:
                name: ### company config
```
