### ISSUE TITLE
fpro only picking up the last .toml file

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#191]
When using multiple `.toml` files, only the last one in alphabetical order is picked up by fpro.

Take the following two files.
`a.toml`
```toml
[[cron]]
  schedule = "*/5 * * * *"
  [cron.job]
    type = "FiveJob"
    queue = "critical"
    [cron.job.custom]
      foo = "bar"

[[cron]]
  schedule = "12 * * * *"
  [cron.job]
    type = "HourlyReport"
    retry = 3

[[cron]]
  schedule = "* * * * *"
  [cron.job]
    type = "EveryMinute"
```

`b.toml`
```toml
[[cron]]
  schedule = "*/5 * * * *"
  [cron.job]
    type = "AnotherJob"
    queue = "critical"
```

Faktory will only show `AnotherJob` from `b.toml` and none from `a.toml`
