### ISSUE TITLE
Queue throttling

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#255]
Implement queue throttling.

* [x] User can declare a set of throttled queues within `conf.d/throttles.toml`, allowing N jobs to execute concurrently.
* [x] worker FETCH: will only allow N jobs to be fetched, further act as if queue is empty.
* [x] worker ACK or FAIL: allow a subsequent FETCH to work.
* [x] worker crash: Any jobs associated with a worker whose heartbeat dies will act as if those jobs immediately FAILed.

Example TOML:

```toml
[throttles]
xyz = { concurrency = 10, timeout = 30 }
slow = { concurrency = 1, timeout = 5 }
```

xyz is the name of the queue, concurrency is max number of jobs allowed to be fetched at the same time, timeout is how long the job can execute before the lock is expired and another FETCH will work.  This timeout is necessary for worker process crash, worker process deadlock, etc.
