### ISSUE TITLE
DB persistence not working

### ISSUE THREAD

**Issue by Rudis1261** [contribsys/faktory#423]
- Which Faktory package and version?
 ```
github.com/contribsys/faktory v1.6.2
github.com/contribsys/faktory_worker_go v1.6.0
```

```shell
#docker image
contribsys/faktory latest 8e53c8a72d2e   8 weeks ago    15.4MB
```

I have tried using a couple of different configurations, but I can't seem to test the persistence locally in docker, I also looked at the Kubernetes examples. 

Using this service definition in `docker-compose.yaml`:
```yaml
  faktory:
    image: contribsys/faktory
    privileged: true
    environment:
      FAKTORY_PROVIDER: tcp://localhost:7419
    volumes:
      - ./data/redis.rdb:/var/lib/faktory/db/redis.rdb
    ports:
      - 7419:7419
      - 7420:7420
 ```
 
 Using this as a volume mount, when I `docker-compose down -v`, then `docker-compose up` I seem to be losing all my data. Is `/var/lib/faktory/db/redis.rdb` still the correct file in the container?

**Comment by Rudis1261** [comment]
When I bash into the container:

```shell
docker run -it contribsys/faktory sh
/ # ls -alhtr /var/lib/faktory/db/
total 8K     
drwxr-xr-x    3 root     root        4.0K Oct  3 19:20 ..
drwxr-xr-x    2 root     root        4.0K Oct  3 19:20 .
```

**Comment by Rudis1261** [comment]
Found: `/root/.faktory/db/faktory.rdb` is this the correct file?

**Comment by mperham** [comment]
It puts the file in /var when running in production mode.  Sounds like it’s in development mode.

**Comment by Rudis1261** [comment]
So a valid service definition would be?
```yaml
  faktory:
    image: contribsys/faktory
    environment:
      FAKTORY_PROVIDER: tcp://localhost:7419
      Environment: production
    volumes:
      - ./data:/var/lib/faktory
    ports:
      - 7419:7419
      - 7420:7420
```

**Comment by mperham** [comment]
FAKTORY_ENV=production

**Comment by Rudis1261** [comment]
Awesome thanks, lemme try that

**Comment by Rudis1261** [comment]
These don't indicate that specific ENV:
https://github.com/contribsys/faktory/wiki/Installation#docker
https://hub.docker.com/r/contribsys/faktory/

**Comment by Rudis1261** [comment]
Hmm still no joy:

```yaml
  faktory:
    image: contribsys/faktory
    environment:
      FAKTORY_PROVIDER: tcp://:secret@localhost:7419
      FAKTORY_ENV: production
      FAKTORY_PASSWORD: secret
    volumes:
      - ./data:/var/lib/faktory/db
    ports:
      - 7419:7419
      - 7420:7420
```

Whether or not I touch the file `./data/redis.rdb`, it crashes when I start the container:
```shell
distributor-faktory-1      | W 2022-12-01T13:16:35.001Z Redis at /var/lib/faktory/db crashed: exit status 1
certificate_distributor-faktory-1      | panic: exit status 1
certificate_distributor-faktory-1      | 
certificate_distributor-faktory-1      | goroutine 7 [running]:
certificate_distributor-faktory-1      | github.com/contribsys/faktory/storage.bootRedis.func2()
certificate_distributor-faktory-1      |        /Users/mperham/src/github.com/contribsys/faktory/storage/redis.go:160 +0xb4
certificate_distributor-faktory-1      | created by github.com/contribsys/faktory/storage.bootRedis
certificate_distributor-faktory-1      |        /Users/mperham/src/github.com/contribsys/faktory/storage/redis.go:156 +0x83c
```

**Comment by Rudis1261** [comment]
Running into all sorts of segmentation faults etc. I am thinking it's got something to do with Mac volume mounts specifically. 

This "works" as in the app fires up, but then seg-faults when I try and enqueue a job

```yaml
version: '3.4'

services:
  faktory:
    image: contribsys/faktory
    environment:
      FAKTORY_PROVIDER: tcp://:secret@localhost:7419
      FAKTORY_ENV: production
      FAKTORY_PASSWORD: secret
    volumes:
      - faktory-data:/var/lib/faktory/db
    ports:
      - 7419:7419
      - 7420:7420

volumes:
  faktory-data:
```
