### ISSUE TITLE
SELinux is preventing /faktory from execmod access for 1.3.0+ versions

### ISSUE THREAD

**Issue by olehpalii-nc** [contribsys/faktory#501]
We recently upgraded from Rocky8 to Rocky9 with SELinux enabled on our Kubernetes (RKE2) nodes and `faktory:latest` started crashing. I tried different version and the last version which works - `1.2.0`.

```
SELinux is preventing /faktory from execmod access on the file /faktory.

*****  Plugin restorecon (88.2 confidence) suggests   ************************

If you want to fix the label.
/faktory default label should be etc_runtime_t.
Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.
Do
# /sbin/restorecon -v /faktory

*****  Plugin catchall_boolean (7.51 confidence) suggests   ******************

If you want to allow selinuxuser to execmod
Then you must tell SELinux about this by enabling the 'selinuxuser_execmod' boolean.

Do
setsebool -P selinuxuser_execmod 1

*****  Plugin catchall_labels (4.88 confidence) suggests   *******************

If you want to allow faktory to have execmod access on the faktory file
Then you need to change the label on /faktory
Do
# semanage fcontext -a -t FILE_TYPE '/faktory'
where FILE_TYPE is one of the following: anon_inodefs_t, autofs_t, binfmt_misc_fs_t, bpf_t, capifs_t, cgroup_t, cifs_t, container_file_t, debugfs_t, device_t, devpts_t, dosfs_t, ecryptfs_t, efivarfs_t, fusefs_t, hugetlbfs_t, iso9660_t, nfs_t, nfsd_fs_t, onload_fs_t, oracleasmfs_t, proc_t, proc_xen_t, pstore_t, removable_t, rpc_pipefs_t, security_t, spufs_t, sysctl_fs_t, sysctl_t, sysfs_t, system_map_t, sysv_t, textrel_shlib_t, tmpfs_t, tracefs_t, unlabeled_t, usbfs_t, virtiofs_t, vmblock_t, xenfs_t.
Then execute:
restorecon -v '/faktory'


*****  Plugin catchall (1.37 confidence) suggests   **************************

If you believe that faktory should be allowed execmod access on the faktory file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'faktory' --raw | audit2allow -M my-faktory
# semodule -X 300 -i my-faktory.pp


Additional Information:
Source Context                system_u:system_r:unconfined_service_t:s0
Target Context                system_u:object_r:var_lib_t:s0
Target Objects                /faktory [ file ]
Source                        faktory
Source Path                   /faktory
Port                          <Unknown>
Source RPM Packages
Target RPM Packages
SELinux Policy RPM            selinux-policy-targeted-38.1.45-3.el9_5.noarch
Local Policy RPM              selinux-policy-targeted-38.1.45-3.el9_5.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Platform                      Linux
                              5.14.0-503.29.1.el9_5.x86_64 #1 SMP
                              PREEMPT_DYNAMIC Wed Mar 5 20:42:50 UTC 2025 x86_64
                              x86_64
Alert Count                   7078
First Seen                    2025-03-18 10:36:19 UTC
Last Seen                     2025-04-12 17:31:01 UTC
Local ID                      c9400592-8768-45e9-b936-de45ef30b983

Raw Audit Messages
type=AVC msg=audit(1744479061.478:375637): avc:  denied  { execmod } for  pid=122349 comm="faktory" path="/faktory" dev="dm-0" ino=202199685 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=file permissive=0


type=SYSCALL msg=audit(1744479061.478:375637): arch=x86_64 syscall=mprotect success=no exit=EACCES a0=7f0f97496000 a1=189e a2=5 a3=12 items=0 ppid=122240 pid=122349 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm=faktory exe=/faktory subj=system_u:system_r:unconfined_service_t:s0 key=(null)

Hash: faktory,unconfined_service_t,var_lib_t,file,execmod
```

I randomly tried to set different options for securityContext, like `privileged: true`, `seLinuxOptions.level: "s0"`, `seLinuxOptions.type: "spc_t"`, etc., but nothing helped.

Also I noticed that there are no SELinux labels inside the faktory container:
```bash
/ # ls -lZ /faktory 
-rwxr-xr-x 1 root root ? 10639737 Jan  2  2020 /faktory
```
 although another container (built from `node:18-bookworm-slim`) in the same pod has such SELinux labels:
```bash
node@api-76d976b659-t9fhb:~/app$ ls -laZ ~/app/yarn.lock  
-rw-r--r--. 1 node node system_u:object_r:container_file_t:s0 993921 Nov 27 11:45 /home/node/app/yarn.lock
```
so, I think it might have something to do with docker image build sequence.

The deployment is very simple:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - image: gcr.io/myproject/api:dev
          name: api
          ports:
            - containerPort: 8911
              name: http
        - image: contribsys/faktory:1.9.1
          name: faktory
          ports:
            - containerPort: 7419
              hostPort: 7419
              name: faktory-7419
            - containerPort: 7420
              hostPort: 7420
              name: faktory-7420
```

Could you kindly advise on how this problem might be addressed?
